<a href="https://colab.research.google.com/github/rajsecrets01/PyTorch/blob/main/00_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


## Intro to tensors
### Creating tensors

In [ ]:
# scalar
scalar = torch.tensor(150000)
scalar

tensor(150000)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

150000

In [ ]:
#get tensor back as python int
p = scalar.item()
type(p)

int

In [ ]:
# vector
vector = torch.tensor([1,488,455])
vector

tensor([  1, 488, 455])

In [ ]:
vector.ndim
# no of square brackets on the ([1,488,455])

1

In [ ]:
vector.shape

torch.Size([3])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                       [18,155]])
MATRIX

tensor([[  7,   8],
        [ 18, 155]])

In [ ]:
MATRIX.ndim
# no of square brackets

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#indexing
MATRIX[0]

tensor([7, 8])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,8,9],
                        [7,9,6]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 8, 9],
         [7, 9, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
tp = torch.tensor([[[[4,5,6,4],
                     [7,8,9,41],
                     [7,8,9,4]]]])

In [ ]:
tp

tensor([[[[ 4,  5,  6,  4],
          [ 7,  8,  9, 41],
          [ 7,  8,  9,  4]]]])

In [ ]:
tp.ndim

4

In [ ]:
tp.shape

torch.Size([1, 1, 3, 4])

### Random Tensors
 Why random tensors ?
 ##### -> neural networks choose random numbers first and then iterate it again and again, to get the most accurate orientation.

In [ ]:
ten1 = torch.rand(3,3)
ten1

# row and columns

tensor([[0.5217, 0.4346, 0.0665],
        [0.2753, 0.5097, 0.3808],
        [0.4715, 0.8186, 0.0438]])

In [ ]:
ten2 = torch.rand(3,4)
ten2

tensor([[0.6517, 0.6051, 0.3114, 0.8808],
        [0.0850, 0.5968, 0.3938, 0.6083],
        [0.9391, 0.6794, 0.1844, 0.2286]])

In [ ]:
ten2.ndim

2

In [ ]:
colour_tensor = torch.rand(size = (240,240,3)) #size and colour channels - R G B colour
colour_tensor

tensor([[[0.9762, 0.9575, 0.1148],
         [0.1028, 0.6066, 0.4498],
         [0.1087, 0.5562, 0.7414],
         ...,
         [0.2385, 0.6214, 0.6091],
         [0.5191, 0.0587, 0.8800],
         [0.0948, 0.1245, 0.4662]],

        [[0.2772, 0.1322, 0.9752],
         [0.1151, 0.7860, 0.1089],
         [0.4500, 0.9451, 0.0808],
         ...,
         [0.4366, 0.2127, 0.4883],
         [0.7890, 0.8813, 0.5293],
         [0.1414, 0.9382, 0.8664]],

        [[0.4174, 0.0558, 0.6420],
         [0.2105, 0.0282, 0.3229],
         [0.3475, 0.7116, 0.5538],
         ...,
         [0.8976, 0.9480, 0.8025],
         [0.4968, 0.9584, 0.8338],
         [0.3030, 0.1038, 0.1517]],

        ...,

        [[0.0693, 0.9029, 0.5899],
         [0.7987, 0.6444, 0.6643],
         [0.0297, 0.9961, 0.2959],
         ...,
         [0.4001, 0.5111, 0.3833],
         [0.9475, 0.5172, 0.2338],
         [0.2814, 0.2467, 0.0074]],

        [[0.6573, 0.9526, 0.8906],
         [0.4262, 0.5869, 0.0570],
         [0.

In [ ]:
colour_tensor.shape

torch.Size([240, 240, 3])

In [ ]:
colour_tensor.ndim

3

In [ ]:
ten3 = torch.rand(7000,100)
ten3

tensor([[0.9331, 0.5944, 0.4018,  ..., 0.6237, 0.5677, 0.8618],
        [0.5897, 0.6867, 0.0656,  ..., 0.8387, 0.8942, 0.2673],
        [0.9051, 0.9709, 0.8713,  ..., 0.8780, 0.4269, 0.5882],
        ...,
        [0.2212, 0.2325, 0.3739,  ..., 0.1787, 0.8628, 0.5565],
        [0.9148, 0.4957, 0.0740,  ..., 0.9178, 0.5373, 0.8516],
        [0.2238, 0.8917, 0.8933,  ..., 0.3112, 0.5465, 0.7574]])

### Zeroes and Ones and like tensors

In [ ]:
# Create a tensor of all zeroes
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ten2.dtype
# default dtatype for tensor random

torch.float32

### Creating tensors in a range

In [ ]:
# use torch.range()  : don't use it because it is deprecated already
torch.range(1,88)

<ipython-input-31-e92c82bb72d7>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,88)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
        29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41., 42.,
        43., 44., 45., 46., 47., 48., 49., 50., 51., 52., 53., 54., 55., 56.,
        57., 58., 59., 60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70.,
        71., 72., 73., 74., 75., 76., 77., 78., 79., 80., 81., 82., 83., 84.,
        85., 86., 87., 88.])

In [ ]:
# use torch.arange()
torch.arange(1,88)

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87])

Results in range and arange are different so arange is more preferable to use.

In [ ]:
torch.__version__

'2.0.1+cu118'

In [ ]:
# stepping is the equal steps you want to go
stepping = torch.arange(start = 0, end = 1000, step = 150)
stepping

tensor([  0, 150, 300, 450, 600, 750, 900])

In [ ]:
stepping.shape

torch.Size([7])

In [ ]:
# creating tensors like : create a tensor with same shape without knowing the 'shape' of the original one
like_tensor = torch.zeros_like(input = stepping)
like_tensor

tensor([0, 0, 0, 0, 0, 0, 0])

In [ ]:
like_tensor.shape

torch.Size([7])

### Tensor datatypes
**Note** : 3 big errors we will face with pytorch and machine learning
1. tensors not right datatype
2. tensors not right shape
3. tensors not on the right device

In [ ]:
# float 32 tensor
float_32_ten = torch.tensor([3.0,5.0, 6.7],
                            dtype = None)

In [ ]:
float_32_ten.dtype

torch.float32

In [ ]:
float_32_ten04 = torch.tensor([3.0,5.0, 6.7],
                            dtype = None,
                            device = None,
                            requires_grad = False)

In [ ]:
float_32_ten02 = torch.tensor([3.0,5.0, 6.7])
float_32_ten02

tensor([3.0000, 5.0000, 6.7000])

In [ ]:
float_32_ten02.dtype

torch.float32

In [ ]:
# float 16 tensor
# way : 01
float_16_ten03 = torch.tensor([3.0,5.0, 6.7],
                            dtype = torch.float16)
float_16_ten03

tensor([3.0000, 5.0000, 6.6992], dtype=torch.float16)

In [ ]:
#  way : 02
float_16_tensor =float_32_ten02.type(torch.float16)
float_16_tensor

tensor([3.0000, 5.0000, 6.6992], dtype=torch.float16)

In [ ]:
# multply the tensors with different datatypes
multiply_tensors = float_32_ten02 * float_16_tensor
multiply_tensors

tensor([ 9.0000, 25.0000, 44.8848])

In [ ]:
multiply_tensors.dtype

torch.float32

*** if we multiply the float16 with float32 we get float 32 ***

In [ ]:
int_32_tensor = torch.tensor([3,6,9,15], dtype = torch.complex32)
int_32_tensor.dtype

<ipython-input-47-f3283fafa392>:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at ../aten/src/ATen/EmptyTensor.cpp:31.)
  int_32_tensor = torch.tensor([3,6,9,15], dtype = torch.complex32)


torch.complex32

### getting info from tensors
**Note** : 3 big errors we will face with pytorch and machine learning
1. tensors not right datatype - to do get datatype from a tensor , can use tensor.type
2. tensors not right shape - to get shape from a tensor, can use tensor.shape
3. tensors not on the right device - to get device from a tensor , can use tensor.device

In [ ]:
#create a tensor
some_tensor = torch.rand(2,5)
some_tensor

tensor([[0.5061, 0.6673, 0.8928, 0.9790, 0.3046],
        [0.8744, 0.8526, 0.4619, 0.2336, 0.2073]])

In [ ]:
#find out detials about some tensor
print(some_tensor)

tensor([[0.5061, 0.6673, 0.8928, 0.9790, 0.3046],
        [0.8744, 0.8526, 0.4619, 0.2336, 0.2073]])


In [ ]:
print(f"datatype : {some_tensor.dtype}")   #datatype

datatype : torch.float32


In [ ]:
print(f"shape : {some_tensor.shape}")  #shape of tensor

shape : torch.Size([2, 5])


In [ ]:
some_tensor.size()   #size of the tensor

torch.Size([2, 5])

In [ ]:
some_tensor.device

device(type='cpu')

### 19. Manipulating tensors (tensors operations)

tensor operations include:
* addition
* subtraction
* multiplication
* division
* matrix multiplication

In [ ]:
t01 = torch.tensor([[1,2,3],
                 [5,8,9],
                 [9,10,11]])
t01

tensor([[ 1,  2,  3],
        [ 5,  8,  9],
        [ 9, 10, 11]])

In [ ]:
# Add
t01 + 1

tensor([[ 2,  3,  4],
        [ 6,  9, 10],
        [10, 11, 12]])

In [ ]:
# Pytorch built-in function for add
torch.add(t01,10)

tensor([[11, 12, 13],
        [15, 18, 19],
        [19, 20, 21]])

In [ ]:
# Substract
t01 - 1

tensor([[ 0,  1,  2],
        [ 4,  7,  8],
        [ 8,  9, 10]])

In [ ]:
# Pytorch built-in function for substract
torch.sub(t01,10)

tensor([[-9, -8, -7],
        [-5, -2, -1],
        [-1,  0,  1]])

In [ ]:
# Multiply
t02 = t01 * 2
t02

tensor([[ 2,  4,  6],
        [10, 16, 18],
        [18, 20, 22]])

In [ ]:
# Pytorch built-in function for multiply
torch.mul(t01,10)

tensor([[ 10,  20,  30],
        [ 50,  80,  90],
        [ 90, 100, 110]])

In [ ]:
# Divide
t02 / 2

tensor([[ 1.,  2.,  3.],
        [ 5.,  8.,  9.],
        [ 9., 10., 11.]])

In [ ]:
# Pytorch built-in function for divide
torch.div(t01,10)

tensor([[0.1000, 0.2000, 0.3000],
        [0.5000, 0.8000, 0.9000],
        [0.9000, 1.0000, 1.1000]])

In [ ]:
t01  #print t01

tensor([[ 1,  2,  3],
        [ 5,  8,  9],
        [ 9, 10, 11]])

In [ ]:
t02  #print t02

tensor([[ 2,  4,  6],
        [10, 16, 18],
        [18, 20, 22]])

In [ ]:
# Matrix mupltiplication
t02 * t01

tensor([[  2,   8,  18],
        [ 50, 128, 162],
        [162, 200, 242]])

In [ ]:
# Pytorch built-in function for matrix multiplication
torch.matmul(t01,t02)

tensor([[ 76,  96, 108],
        [252, 328, 372],
        [316, 416, 476]])

### Matrix Multiplication

two things are there :
1. Element wise
2. Matrix multiplication (dot product)  :
  * (3,2) and (2,4) : its first and last no should match
  * the resulting matrix is (3,4)

In [ ]:
ten07 = torch.tensor([1,2,3])
ten07

tensor([1, 2, 3])

In [ ]:
# element wise multiplication
print(ten07, "*" ,ten07)
print(f"equals : {ten07 * ten07}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals : tensor([1, 4, 9])


In [ ]:
# dot product , matrix multiplication
torch.matmul(ten07, ten07)

tensor(14)

In [ ]:
ten07 = torch.rand(3,3)

In [ ]:
%%time
value = 0
for i in range (len(ten07)):
  value += ten07[i] + ten07[i]

print(value)

tensor([2.6588, 2.1603, 2.8620])
CPU times: user 1.14 ms, sys: 0 ns, total: 1.14 ms
Wall time: 1.15 ms


In [ ]:
%%time
torch.matmul(ten07, ten07)

CPU times: user 2.33 ms, sys: 0 ns, total: 2.33 ms
Wall time: 12.8 ms


tensor([[0.9543, 0.5199, 0.8705],
        [0.3132, 0.5578, 0.5096],
        [0.3902, 0.3729, 0.5279]])

In [ ]:
tensor_a = torch.tensor([[1,5,5],
                        [5,8,9]])
tensor_a.shape

torch.Size([2, 3])

In [ ]:
tensor_b = torch.tensor([[5,7],
                         [4,6],
                         [8,6]])
tensor_b.shape

torch.Size([3, 2])

In [ ]:
# matrix transpose
tesnsor_b_transpose = tensor_b.T
tesnsor_b_transpose.shape

torch.Size([2, 3])

***Transpose of the matrix, will transforms its order and 2,3 will be 3,2.***

In [ ]:
mul = torch.matmul(tensor_a, tensor_b)

In [ ]:
mul

tensor([[ 65,  67],
        [129, 137]])

### Finding the min, max, sum,mean, etc (tensor aggregation)

In [ ]:
tensor08 = torch.tensor([[5,7,50],
                         [4,6,66],
                         [8,6,99]])

* minimum

In [ ]:
tensor08.min()

tensor(4)

In [ ]:
torch.min(tensor08)

tensor(4)

* maximum

In [ ]:
tensor08.max()

tensor(99)

In [ ]:
torch.max(tensor08)

tensor(99)

* mean

In [ ]:
#  tensor08.mean() # Error :  tensor is not right datatype

In [ ]:
tensor08.dtype

torch.int64

In [ ]:
# now we will change the datatype int64 to float32 or float64
tensor08_float = tensor08.type(torch.float64)
tensor08_float.dtype

torch.float64

In [ ]:
tensor08_float.mean()

tensor(27.8889, dtype=torch.float64)

In [ ]:
torch.mean(tensor08_float)

tensor(27.8889, dtype=torch.float64)

* sum

In [ ]:
tensor08_float.sum()

tensor(251., dtype=torch.float64)

In [ ]:
torch.sum(tensor08_float)

tensor(251., dtype=torch.float64)

In [ ]:
# sum will work with the datatype int64 unlike mean (>> which works only on float)
tensor08.sum()

tensor(251)

In [ ]:
tensor08_float

tensor([[ 5.,  7., 50.],
        [ 4.,  6., 66.],
        [ 8.,  6., 99.]], dtype=torch.float64)

### Finding the positional min and max

* argmin

In [ ]:
# index value of the minimum no. in the matrix
tensor08_float.argmin()

tensor(3)

In [ ]:
tensor08_float.min()

tensor(4., dtype=torch.float64)

* argmax

In [ ]:
# index value of the maximum no. in the matrix
tensor08_float.argmax()

tensor(8)

In [ ]:
tensor08_float.max()

tensor(99., dtype=torch.float64)

# Practice

In [ ]:
ten09 = torch.rand(3,4)

In [ ]:
ten09

tensor([[0.9809, 0.8452, 0.0452, 0.4649],
        [0.0528, 0.1114, 0.7343, 0.8209],
        [0.1929, 0.0547, 0.6263, 0.5399]])

In [ ]:
ten09.argmax()

tensor(0)

In [ ]:
ten09.max()

tensor(0.9809)

### Reshaping , viewing , stacking , squeezing and unsqueezing tensors
* Reshaping - reshapes a tensor
* View - Data same different shape
* stacking combine multiple tensors on top of each other (vstack) and (hstack)
  * vstack = on each other
  * hstack = side by side
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
import torch

In [ ]:
x = torch.arange(1., 10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# add an extra dimensionn to it
x_reshaped = x.reshape(9,1)
x, x_reshaped

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]))

In [ ]:
x_reshaped = x.reshape(3,3)
x, x_reshaped

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]))

In [ ]:
#change the view
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x.view(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
x.view(9,1) , x

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Stack the tensors on top of each other
xstack = torch.stack([x, x, x, x, x], dim = 0)
xstack

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
xstack.ndim

2

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
# torch.squeeze()

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [ ]:
# torch unsqueeze() - adds a single dimension to a target at a specific dim
y_unsqueezed = y.unsqueeze(dim=0)
y_unsqueezed.size()

torch.Size([1, 2, 2, 2])

In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [ ]:
x

tensor([[[ 1.3873, -0.5155, -0.9850, -0.5256,  1.3886],
         [-0.3813,  0.2803,  0.2940,  0.8204,  0.5220],
         [ 1.0495,  0.8096, -0.4465,  0.5234, -0.2216]],

        [[ 0.6203, -1.3261,  0.6436,  0.0718, -0.1979],
         [-0.3703, -1.0550, -0.0641,  0.6756,  0.9016],
         [ 0.0864, -0.5698,  1.4087, -0.8290, -0.8197]]])

In [ ]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])

In [ ]:
p = torch.rand(44,10,52,40)
p.ndim

4