<a href="https://colab.research.google.com/github/rajsecrets01/PyTorch/blob/main/01_pytorch_fundamentals_video.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Indexing (selecting data from tensors)
Indexing with Pytorch is similar to indexing with Numpy


In [1]:
# create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# let's index on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [3]:
# let's index on the middle bracket (dim=1)
x[0,0]

tensor([1, 2, 3])

In [4]:
# inner most bracket indexing of numbers
x[0][1][2]
# here [1] - is showing rows
# here [2] - is showing columns
# indexing always starts from 0

tensor(6)

In [5]:
# get 9 by indexing
x[0][2][2]

tensor(9)

In [6]:
# you can also use ":" to select all the of target dimension
x[:,0]

tensor([[1, 2, 3]])

In [7]:
# Get all values of 0th and 1st dim but only index 1 of 2nd dim
x[:,:,2]

tensor([[3, 6, 9]])

In [8]:
# get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:,1,1]

tensor([5])

In [9]:
# get the 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [10]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [11]:
# index on x to return 9
x[:,2,2]

tensor([9])

In [12]:
# index on x to return 3,6,9
x[:,:,2]

tensor([[3, 6, 9]])

## Pytorch tensors and Numpy
* Data in Numpy, want in Pytorch Tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> Numpy -> `torch.Tensor.numpy()`

In [13]:
# Numpy array to tensor
import torch
import numpy as np


array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)

In [14]:
array, tensor, array.dtype, tensor.dtype , print("numpy default decimal : float32")

numpy default decimal : float32


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 dtype('float64'),
 torch.float64,
 None)

In [15]:
array02 = np.arange(1,10)
tensor02 = torch.from_numpy(array02)
tensor02

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# now we will change the array and see what it's effect on tensor
array = array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

* Tensor will not change if you will change *array*

In [17]:
# Tensor to Numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()

* Now we will change the tensor and see what it's effect on numpy array


In [18]:
tensor = tensor + 1

In [19]:
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [20]:
numpy_tensor.dtype

dtype('float32')

In [21]:
tensor.dtype

torch.float32

## Reproducibility (trying to make random out of random)

`start with random no. -> tensor operation -> update the random nos. and update them -> again -> again -> again...`

To reduce the randomness in neural networks and Pytorch comes with the concept of **RANDOM SEED**
Essentially what the random seed does is "flavour" the randomness.



In [22]:
torch.rand(3,3)

tensor([[0.6625, 0.9323, 0.7506],
        [0.2855, 0.6097, 0.6491],
        [0.1883, 0.1971, 0.0755]])

In [23]:
random_A = torch.rand(3,4)
random_B = torch.rand(3,4)
print(random_A)
print(random_B)
print(random_A == random_B)

tensor([[0.8495, 0.3784, 0.9044, 0.4137],
        [0.7603, 0.5610, 0.0536, 0.5251],
        [0.8154, 0.0543, 0.8142, 0.3046]])
tensor([[0.6816, 0.4753, 0.9652, 0.3651],
        [0.2198, 0.0655, 0.1214, 0.1195],
        [0.2930, 0.4306, 0.7057, 0.9623]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


### Random seed - It sets the randomness

In [28]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_c = torch.rand(3,5)

torch.manual_seed(RANDOM_SEED)
random_d = torch.rand(3,5)

print(random_c)
print(random_d)
print(random_c == random_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
        [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411]])
tensor([[True, True, True, True, True],
        [True, True, True, True, True],
        [True, True, True, True, True]])


## Running tenors and Pytorch objects on GPUs (and making faster computations)

* GPUs = faster computation on no.
Because of CUDA + NVIDIA + Pytorch backend

### 1. Getting a GPU
* Use GCP +++
* Purchase
* Cloud Computing - GCP, AWS , Azure

In [4]:
!nvidia-smi

Sun Aug 27 04:48:46 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8    10W /  70W |      3MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [5]:
# check for GPU with Pytorch
import torch
torch.cuda.is_available()

True

For PyTorch if it is capable of running compute on GPU or CPU, it is best practice to setup device agnostic code
E.g. run on GPU if available, else CPU

In [6]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [7]:
# Count no of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and models) on CPU
* For faster computation

In [16]:
# create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device = "cpu")

# Tensor on CPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


On **GPU**:

Way 1

In [17]:
# create a tensor on GPU - cuda
tensor = torch.tensor([1,2,3], device = "cuda")

# Tensor on GPU
print(tensor, tensor.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


On GPU:

Way 2

In [20]:
# tensor on GPU (Better method , if GPU is not available then it will use CPU)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors to CPU


In [22]:
# if tensor is on GPU, then it cannot transform in to numpy
# tensor_on_gpu.numpy()

In [24]:
# To fix the issues, go to CPU by using ".cpu()"
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])